### ISSUE TITLE
OSError: symbolic link privilege not held 

### ISSUE THREAD

**Issue by MastafaF** [megagonlabs/ginza#40] opened 2019-08-23 10:40 UTC
Hi, 

I want to use Ginza with spacy on Windows. I have the following error when running the code on python 3: 
Code: 
`import spacy
nlp = spacy.load('ja_ginza')
doc = nlp('依存構造解析の実験を行っています。')
for sent in doc.sents:
    for token in sent:
        print(token.i, token.orth_, token.lemma_, token.pos_, token.tag_, token.dep_, token.head.i)
    print('EOS')`
**Error1**: ModuleNotFoundError: No module named 'sudachidict'
During handling of the above exception, another exception occurred:
**Error2**: OSError: symbolic link privilege not held 

I followed the instructions given on the Github page after **pip install "https://github.com/megagonlabs/ginza/releases/download/latest/ginza-latest.tar.gz"** . And when running command "ginza" on Anaconda prompt, I have the **same error**. 

Should I remove sudachipy before running "ginza"? 
Could you please let me know what is the solution to this problem?

Great idea integrating it to spacy btw.

**Comment by MastafaF** [comment] 2019-08-23 15:41
For possible readers having the same issue, the solution is to run Anaconda prompt or Command Prompt as **administrator**. 
However, I find unclear the following instructions: 
**

> Add ginza command
> run ginza from the console
> Change package structure
> module package as ginza
> language model package as ja_ginza
> spacy.lang.ja is overridden by ginza
> Remove sudachipy related directories
> SudachiPy and its dictionary are installed via pip during ginza installation
> User dictionary available
> See Customized dictionary - SudachiPy

**

Should we remove sudachipy and why should we do so given that SudachiPy seems to be the morphological analyser behind Ginza? 

Thank you for clarifying the instructions if possible for Windows users.

**Comment by hiroshi-matsuda-rit** [comment] 2019-09-29 15:38
@MastafaF Thank you for reporting the install problem on Anaconda enveironment.
I heard there are some common problems while using pip over Anaconda.
I've been testing GiNZA on the latest release version of python3 but actually not for Anaconda.
I'd like to try to use Anaconda in future but it might take few months. Sorry for that.

**Comment by hiroshi-matsuda-rit** [comment] 2019-09-30 02:03
I succeeded to install GiNZA in the standard `pip install` procedure on Mac OS 10.14.6 with Xcode 9.4.1, python 3.7.4, pip 19.0.3, Cython-0.29.13, spaCy-2.1.8, SudachiPy-9.4.0.
I'd try to change Xcode to the latest version 11.0.

**Comment by chezou** [comment] 2019-11-28 14:38
This issue is not Anaconda specific issue. Since Windows requires administrator privileges to make a symlink, the issue occurs with an environment based on official PSF Python. Looking at the error message, it seems root cause came from sudachipy.

```
λ  python
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> nlp = spacy.load('ja_ginza')
Traceback (most recent call last):
  File "C:\Users\chezo\source\ginza-test\.venv\lib\site-packages\sudachipy\config.py", line 55, in create_default_link_for_sudachidict_core
    dict_path = Path(import_module('sudachidict').__file__).parent
  File "C:\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sudachidict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\chezo\source\ginza-test\.venv\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "C:\Users\chezo\source\ginza-test\.venv\lib\site-packages\spacy\util.py", line 164, in load_model
    return load_model_from_package(name, **overrides)
  File "C:\Users\chezo\source\ginza-test\.venv\lib\site-packages\spacy\util.py", line 185, in load_model_from_package
    return cls.load(**overrides)
  File "C:\Users\chezo\source\ginza-test\.venv\lib\site-packages\ja_ginza\__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "C:\Users\chezo\source\ginza-test\.venv\lib\site-packages\spacy\util.py", line 228, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "C:\Users\chezo\source\ginza-test\.venv\lib\site-packages\spacy\util.py", line 197, in load_model_from_path
    nlp = cls(meta=meta, **overrides)
  File "C:\Users\chezo\source\ginza-test\.venv\lib\site-packages\spacy\language.py", line 173, in __init__
    make_doc = factory(self, **meta.get("tokenizer", {}))
  File "C:\Users\chezo\source\ginza-test\.venv\lib\site-packages\ginza\__init__.py", line 49, in create_tokenizer
    return SudachiTokenizer(nlp)
  File "C:\Users\chezo\source\ginza-test\.venv\lib\site-packages\ginza\sudachi_tokenizer.py", line 73, in __init__
    dict_ = dictionary.Dictionary()
  File "C:\Users\chezo\source\ginza-test\.venv\lib\site-packages\sudachipy\dictionary.py", line 37, in __init__
    self._read_system_dictionary(config.settings.system_dict_path())
  File "C:\Users\chezo\source\ginza-test\.venv\lib\site-packages\sudachipy\config.py", line 106, in system_dict_path
    dict_path = create_default_link_for_sudachidict_core(output=f)
  File "C:\Users\chezo\source\ginza-test\.venv\lib\site-packages\sudachipy\config.py", line 71, in create_default_link_for_sudachidict_core
    dict_path = set_default_dict_package('sudachidict_core', output=output)
  File "C:\Users\chezo\source\ginza-test\.venv\lib\site-packages\sudachipy\config.py", line 47, in set_default_dict_package
    dst_path.symlink_to(src_path)
  File "C:\Python36\lib\pathlib.py", line 1325, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
  File "C:\Python36\lib\pathlib.py", line 393, in wrapped
    return strfunc(str(pathobjA), str(pathobjB), *args)
OSError: symbolic link privilege not held
```

**Comment by chezou** [comment] 2019-11-28 15:04
Created a ticket to sudachipy issue https://github.com/WorksApplications/SudachiPy/issues/107

**Comment by hiroshi-matsuda-rit** [comment] 2020-01-17 15:23
From v3.1.0, GiNZA started to use original dictionary package, 'ja_ginza_dict'.
I'd close this issue because above errors were caused by SudachiDict package.

**Closed by hiroshi-matsuda-rit** 2020-01-17 15:23 UTC
